FROM node:20.9.0-alpine
ENV NODE_ENV=production
RUN mkdir /medusa-app
WORKDIR /medusa-app
COPY . .
#COPY .env.dev .env
WORKDIR /medusa-app/backend
RUN yarn install 
EXPOSE 9000
CMD sh -c "free -m && yarn start"
